version: '3.8'

services:
  frontend:
    image: openresponse_frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: "http://localhost:3001"
    networks:
      - openresponse_network

  backend:
    image: openresponse_backend
    ports:
      - "3001:3001"
    environment:
      DEV_DB_HOST: db
      DEV_DB_PORT: 3306
      DEV_DB_PASS: password
      TEST_DB_HOST: db
      TEST_DB_PORT: 3306
      TEST_DB_PASS: password
    depends_on:
      - db
    entrypoint: ["./entrypoint.sh"]
    networks:
      - openresponse_network

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./core/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -prootpassword || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - openresponse_network

volumes:
  db_data:

networks:
  openresponse_network:
    driver: bridge
