name: Node.js Test Environment

on:
  pull_request:
    branches: [ "main" , "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['17.9.0', '21.7.3']
    
    env:
      DB_DATABASE: myclassroom_test
      DB_USER: test_admin
      DB_PASSWORD: password

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE IF NOT EXISTS ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Set Up Database
      run:  npx sequelize-cli db:migrate --env test
            npx sequelize-cli db:seed:all --env test
    
    - name: Run Tests
      run: npm test